const state={allSongs:[],filteredSongs:[],selectedId:null,filter:'all',scrollTimer:null,scrollSpeed:3,setlist:[],savedSetlists:readSavedSetlists()};
const dom={musicList:document.getElementById('musicList'),libraryCount:document.getElementById('libraryCount'),searchInput:document.getElementById('searchInput'),viewerTitle:document.getElementById('viewerTitle'),viewerSubtitle:document.getElementById('viewerSubtitle'),metaKey:document.getElementById('metaKey'),metaBpm:document.getElementById('metaBpm'),metaCapo:document.getElementById('metaCapo'),metaSource:document.getElementById('metaSource'),musicContent:document.getElementById('musicContent'),fontRange:document.getElementById('fontRange'),increaseFont:document.getElementById('increaseFont'),decreaseFont:document.getElementById('decreaseFont'),copyText:document.getElementById('copyText'),startScroll:document.getElementById('startScroll'),scrollSpeed:document.getElementById('scrollSpeed'),toggleStageMode:document.getElementById('toggleStageMode'),refreshLibrary:document.getElementById('refreshLibrary'),addToSetlist:document.getElementById('addToSetlist'),setlistList:document.getElementById('setlistList'),setlistCount:document.getElementById('setlistCount'),nextSongCard:document.getElementById('nextSongCard'),nextSong:document.getElementById('nextSong'),prevSong:document.getElementById('prevSong'),jumpInput:document.getElementById('jumpInput'),jumpButton:document.getElementById('jumpButton'),saveSetlist:document.getElementById('saveSetlist'),clearSetlist:document.getElementById('clearSetlist'),setlistTitle:document.getElementById('setlistTitle')};
function normalizeSong(song,origin){return{id:song.id||`${origin}-${song.title}-${song.artist}`.toLowerCase().replace(/\s+/g,'-'),title:song.title||'Sem título',artist:song.artist||'Artista não informado',key:song.key||'—',bpm:song.bpm||'—',capo:song.capo||'—',tags:Array.isArray(song.tags)?song.tags:String(song.tags||'').split(',').map(v=>v.trim()).filter(Boolean),notes:song.notes||'',lyrics:song.lyrics||'',source:origin==='online'?'Online':'Local',sourceType:origin};}
async function fetchOnlineLibrary(){const r=await fetch('content/online-library/manifest.json',{cache:'no-store'});const p=await r.json();return(Array.isArray(p.musics)?p.musics:[]).map(s=>normalizeSong(s,'online'));}
function getLocalLibrary(){return readDraftLibrary().map(s=>normalizeSong(s,'local'));}
function esc(v){return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function highlightLyrics(text){return text.split('\n').map(line=>{const safe=esc(line); if(/^[\[(#].+[\])]?$/.test(line.trim())) return `<span class="section">${safe}</span>`; return safe.replace(/\b([A-G](#|b)?(m|maj7|7|sus2|sus4|dim|add9|9|11|13)?)(\/([A-G](#|b)?))?\b/g,'<span class="chord">$1</span>');}).join('\n');}
function renderList(){const q=dom.searchInput.value.trim().toLowerCase(); state.filteredSongs=state.allSongs.filter(song=>{const mf=state.filter==='all'||song.sourceType===state.filter; const bag=[song.title,song.artist,song.key,song.notes,song.tags.join(' ')].join(' ').toLowerCase(); return mf&&bag.includes(q);}); dom.libraryCount.textContent=`${state.filteredSongs.length} faixas`; dom.musicList.innerHTML=state.filteredSongs.map(song=>`<article class="song-item ${song.id===state.selectedId?'active':''}" data-id="${song.id}"><h3>${song.title}</h3><p>${song.artist} • Tom ${song.key} • ${song.source}</p><div class="song-tags">${(song.tags.length?song.tags:['sem tags']).slice(0,4).map(tag=>`<span class="tag">${tag}</span>`).join('')}</div></article>`).join('')||`<div class="empty-state"><div class="empty-icon">⊘</div><p>Nenhuma música encontrada com esse filtro.</p></div>`; dom.musicList.querySelectorAll('.song-item').forEach(item=>item.addEventListener('click',()=>openSong(item.dataset.id)));}
function renderSetlist(){dom.setlistCount.textContent=`${state.setlist.length} músicas`; const currentIndex=state.setlist.findIndex(song=>song.id===state.selectedId); const nextSong=currentIndex>=0?state.setlist[currentIndex+1]:state.setlist[0]; dom.nextSongCard.textContent=nextSong?`Próxima: ${nextSong.title} — ${nextSong.artist}`:'Nenhuma próxima música'; dom.setlistList.innerHTML=state.setlist.map((song,index)=>`<article class="setlist-item ${song.id===state.selectedId?'active':''}" data-id="${song.id}"><h4>${index+1}. ${song.title}</h4><p>${song.artist} • Tom ${song.key}</p><div class="setlist-inline"><button class="setlist-btn move-up" data-index="${index}" type="button">↑</button><button class="setlist-btn move-down" data-index="${index}" type="button">↓</button><button class="setlist-btn remove-item" data-index="${index}" type="button">Remover</button></div></article>`).join('')||`<div class="empty-state"><div class="empty-icon">♪</div><p>Monte seu repertório para tocar ao vivo.</p></div>`; dom.setlistList.querySelectorAll('.setlist-item').forEach(item=>item.addEventListener('click',()=>openSong(item.dataset.id))); dom.setlistList.querySelectorAll('.move-up').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const i=Number(btn.dataset.index);if(i>0)[state.setlist[i-1],state.setlist[i]]=[state.setlist[i],state.setlist[i-1]];renderSetlist();})); dom.setlistList.querySelectorAll('.move-down').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const i=Number(btn.dataset.index);if(i<state.setlist.length-1)[state.setlist[i+1],state.setlist[i]]=[state.setlist[i],state.setlist[i+1]];renderSetlist();})); dom.setlistList.querySelectorAll('.remove-item').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();state.setlist.splice(Number(btn.dataset.index),1);renderSetlist();}));}
function openSong(id){const song=state.allSongs.find(i=>i.id===id)||state.setlist.find(i=>i.id===id); if(!song)return; state.selectedId=id; dom.viewerTitle.textContent=song.title; dom.viewerSubtitle.textContent=`${song.artist}${song.notes?' • '+song.notes:''}`; dom.metaKey.textContent=song.key||'—'; dom.metaBpm.textContent=song.bpm||'—'; dom.metaCapo.textContent=song.capo||'—'; dom.metaSource.textContent=song.source||'Setlist'; dom.musicContent.innerHTML=highlightLyrics(song.lyrics||'Sem letra/cifra cadastrada.'); renderList(); renderSetlist();}
async function loadLibrary(){try{const online=await fetchOnlineLibrary(); const local=getLocalLibrary(); state.allSongs=[...online,...local]; renderList(); renderSetlist(); if(state.allSongs.length&&!state.selectedId) openSong(state.allSongs[0].id);}catch(e){dom.musicList.innerHTML=`<div class="empty-state"><div class="empty-icon">!</div><p>Não foi possível carregar a biblioteca online.</p></div>`;}}
function setFontSize(size){document.documentElement.style.setProperty('--font-size-viewer',`${size}px`); dom.fontRange.value=size;}
function toggleScroll(){if(state.scrollTimer){clearInterval(state.scrollTimer);state.scrollTimer=null;dom.startScroll.textContent='Auto Scroll';return;} state.scrollTimer=setInterval(()=>window.scrollBy({top:state.scrollSpeed,left:0,behavior:'smooth'}),80); dom.startScroll.textContent='Parar Scroll';}
function addCurrentToSetlist(){const current=state.allSongs.find(i=>i.id===state.selectedId); if(!current)return; state.setlist.push({...current}); renderSetlist();}
function goRelative(delta){if(!state.setlist.length)return; const currentIndex=state.setlist.findIndex(song=>song.id===state.selectedId); const nextIndex=currentIndex===-1?0:Math.min(Math.max(currentIndex+delta,0),state.setlist.length-1); openSong(state.setlist[nextIndex].id);}
function jumpToTrack(){const target=Number(dom.jumpInput.value)-1; if(target>=0&&target<state.setlist.length) openSong(state.setlist[target].id);}
function saveSetlist(){const name=prompt('Nome do repertório:',`Setlist ${new Date().toLocaleDateString('pt-BR')}`); if(!name)return; state.savedSetlists.unshift({id:`setlist-${Date.now()}`,name,createdAt:new Date().toISOString(),songs:state.setlist}); writeSavedSetlists(state.savedSetlists); dom.setlistTitle.textContent=`Setlist atual • ${name}`;}
dom.searchInput.addEventListener('input',renderList); document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(btn=>btn.classList.remove('active')); chip.classList.add('active'); state.filter=chip.dataset.filter; renderList();}));
dom.fontRange.addEventListener('input',e=>setFontSize(e.target.value)); dom.increaseFont.addEventListener('click',()=>setFontSize(Math.min(32,Number(dom.fontRange.value)+1))); dom.decreaseFont.addEventListener('click',()=>setFontSize(Math.max(14,Number(dom.fontRange.value)-1)));
dom.copyText.addEventListener('click',async()=>{const song=state.allSongs.find(i=>i.id===state.selectedId)||state.setlist.find(i=>i.id===state.selectedId); if(!song)return; try{await navigator.clipboard.writeText(song.lyrics||''); dom.copyText.textContent='Copiado'; setTimeout(()=>dom.copyText.textContent='Copiar',1200);}catch(e){}});
dom.startScroll.addEventListener('click',toggleScroll); dom.scrollSpeed.addEventListener('input',e=>{state.scrollSpeed=Number(e.target.value)}); dom.toggleStageMode.addEventListener('click',()=>document.body.classList.toggle('stage-mode')); dom.refreshLibrary.addEventListener('click',loadLibrary); dom.addToSetlist.addEventListener('click',addCurrentToSetlist); dom.nextSong.addEventListener('click',()=>goRelative(1)); dom.prevSong.addEventListener('click',()=>goRelative(-1)); dom.jumpButton.addEventListener('click',jumpToTrack); dom.jumpInput.addEventListener('keydown',e=>{if(e.key==='Enter') jumpToTrack();}); dom.saveSetlist.addEventListener('click',saveSetlist); dom.clearSetlist.addEventListener('click',()=>{state.setlist=[]; renderSetlist();});
setFontSize(19); loadLibrary();